// S&P 500 Stock Data organized by sector
// Market cap in billions, change is daily percentage change (simulated)
const sp500Data = {
    name: "S&P 500",
    children: [
        {
            name: "Technology",
            children: [
                { ticker: "AAPL", name: "Apple Inc.", marketCap: 2890, change: 1.25 },
                { ticker: "MSFT", name: "Microsoft Corp.", marketCap: 2780, change: 0.85 },
                { ticker: "NVDA", name: "NVIDIA Corp.", marketCap: 1200, change: 3.45 },
                { ticker: "AVGO", name: "Broadcom Inc.", marketCap: 580, change: 1.12 },
                { ticker: "ORCL", name: "Oracle Corp.", marketCap: 320, change: -0.45 },
                { ticker: "CRM", name: "Salesforce Inc.", marketCap: 265, change: 0.67 },
                { ticker: "CSCO", name: "Cisco Systems", marketCap: 215, change: -0.32 },
                { ticker: "ACN", name: "Accenture", marketCap: 205, change: 0.28 },
                { ticker: "IBM", name: "IBM Corp.", marketCap: 175, change: -0.15 },
                { ticker: "ADBE", name: "Adobe Inc.", marketCap: 235, change: 1.85 },
                { ticker: "AMD", name: "AMD Inc.", marketCap: 195, change: 2.35 },
                { ticker: "INTC", name: "Intel Corp.", marketCap: 145, change: -1.25 },
                { ticker: "QCOM", name: "Qualcomm", marketCap: 165, change: 0.95 },
                { ticker: "TXN", name: "Texas Instruments", marketCap: 155, change: 0.42 },
                { ticker: "INTU", name: "Intuit Inc.", marketCap: 145, change: 0.78 },
                { ticker: "AMAT", name: "Applied Materials", marketCap: 125, change: 1.65 },
                { ticker: "NOW", name: "ServiceNow", marketCap: 150, change: 1.22 },
                { ticker: "MU", name: "Micron Technology", marketCap: 105, change: 2.15 },
                { ticker: "LRCX", name: "Lam Research", marketCap: 95, change: 1.45 },
                { ticker: "ADI", name: "Analog Devices", marketCap: 90, change: 0.55 }
            ]
        },
        {
            name: "Healthcare",
            children: [
                { ticker: "UNH", name: "UnitedHealth Group", marketCap: 480, change: -0.65 },
                { ticker: "JNJ", name: "Johnson & Johnson", marketCap: 385, change: 0.22 },
                { ticker: "LLY", name: "Eli Lilly", marketCap: 565, change: 2.85 },
                { ticker: "MRK", name: "Merck & Co.", marketCap: 275, change: 0.45 },
                { ticker: "ABBV", name: "AbbVie Inc.", marketCap: 285, change: -0.35 },
                { ticker: "PFE", name: "Pfizer Inc.", marketCap: 165, change: -1.15 },
                { ticker: "TMO", name: "Thermo Fisher", marketCap: 205, change: 0.72 },
                { ticker: "ABT", name: "Abbott Labs", marketCap: 190, change: 0.38 },
                { ticker: "DHR", name: "Danaher Corp.", marketCap: 175, change: 0.55 },
                { ticker: "BMY", name: "Bristol-Myers", marketCap: 115, change: -0.82 },
                { ticker: "AMGN", name: "Amgen Inc.", marketCap: 145, change: 0.28 },
                { ticker: "MDT", name: "Medtronic", marketCap: 110, change: -0.45 },
                { ticker: "GILD", name: "Gilead Sciences", marketCap: 95, change: 0.65 },
                { ticker: "ISRG", name: "Intuitive Surgical", marketCap: 135, change: 1.45 },
                { ticker: "VRTX", name: "Vertex Pharma", marketCap: 105, change: 1.95 },
                { ticker: "CVS", name: "CVS Health", marketCap: 85, change: -0.55 },
                { ticker: "CI", name: "Cigna Group", marketCap: 90, change: 0.35 },
                { ticker: "ELV", name: "Elevance Health", marketCap: 105, change: -0.28 },
                { ticker: "SYK", name: "Stryker Corp.", marketCap: 115, change: 0.88 },
                { ticker: "REGN", name: "Regeneron", marketCap: 95, change: 1.22 }
            ]
        },
        {
            name: "Financials",
            children: [
                { ticker: "BRK.B", name: "Berkshire Hathaway", marketCap: 785, change: 0.45 },
                { ticker: "JPM", name: "JPMorgan Chase", marketCap: 495, change: 0.92 },
                { ticker: "V", name: "Visa Inc.", marketCap: 485, change: 0.65 },
                { ticker: "MA", name: "Mastercard", marketCap: 385, change: 0.78 },
                { ticker: "BAC", name: "Bank of America", marketCap: 265, change: -0.35 },
                { ticker: "WFC", name: "Wells Fargo", marketCap: 185, change: -0.55 },
                { ticker: "GS", name: "Goldman Sachs", marketCap: 135, change: 1.15 },
                { ticker: "MS", name: "Morgan Stanley", marketCap: 145, change: 0.85 },
                { ticker: "BLK", name: "BlackRock", marketCap: 115, change: 0.42 },
                { ticker: "AXP", name: "American Express", marketCap: 155, change: 0.58 },
                { ticker: "SPGI", name: "S&P Global", marketCap: 125, change: 0.72 },
                { ticker: "C", name: "Citigroup", marketCap: 95, change: -0.68 },
                { ticker: "SCHW", name: "Charles Schwab", marketCap: 105, change: 0.35 },
                { ticker: "CB", name: "Chubb Ltd.", marketCap: 95, change: 0.28 },
                { ticker: "PGR", name: "Progressive Corp.", marketCap: 115, change: 1.05 },
                { ticker: "MMC", name: "Marsh McLennan", marketCap: 95, change: 0.45 },
                { ticker: "ICE", name: "Intercontinental Ex", marketCap: 75, change: 0.55 },
                { ticker: "USB", name: "U.S. Bancorp", marketCap: 65, change: -0.42 },
                { ticker: "AON", name: "Aon plc", marketCap: 70, change: 0.38 },
                { ticker: "CME", name: "CME Group", marketCap: 75, change: 0.62 }
            ]
        },
        {
            name: "Consumer Discretionary",
            children: [
                { ticker: "AMZN", name: "Amazon.com", marketCap: 1550, change: 1.45 },
                { ticker: "TSLA", name: "Tesla Inc.", marketCap: 585, change: -2.35 },
                { ticker: "HD", name: "Home Depot", marketCap: 345, change: 0.55 },
                { ticker: "MCD", name: "McDonald's Corp.", marketCap: 205, change: 0.32 },
                { ticker: "NKE", name: "Nike Inc.", marketCap: 145, change: -0.85 },
                { ticker: "LOW", name: "Lowe's Cos.", marketCap: 135, change: 0.48 },
                { ticker: "SBUX", name: "Starbucks", marketCap: 105, change: -0.55 },
                { ticker: "TJX", name: "TJX Companies", marketCap: 115, change: 0.72 },
                { ticker: "BKNG", name: "Booking Holdings", marketCap: 125, change: 1.25 },
                { ticker: "CMG", name: "Chipotle", marketCap: 75, change: 0.95 },
                { ticker: "MAR", name: "Marriott Intl", marketCap: 70, change: 0.45 },
                { ticker: "ORLY", name: "O'Reilly Auto", marketCap: 60, change: 0.38 },
                { ticker: "GM", name: "General Motors", marketCap: 55, change: -1.15 },
                { ticker: "F", name: "Ford Motor", marketCap: 50, change: -0.92 },
                { ticker: "AZO", name: "AutoZone", marketCap: 50, change: 0.55 },
                { ticker: "ROST", name: "Ross Stores", marketCap: 45, change: 0.68 },
                { ticker: "DHI", name: "D.R. Horton", marketCap: 45, change: 1.35 },
                { ticker: "LEN", name: "Lennar Corp.", marketCap: 40, change: 1.22 },
                { ticker: "YUM", name: "Yum! Brands", marketCap: 40, change: 0.28 },
                { ticker: "EBAY", name: "eBay Inc.", marketCap: 25, change: 0.45 }
            ]
        },
        {
            name: "Communication Services",
            children: [
                { ticker: "GOOGL", name: "Alphabet Inc.", marketCap: 1750, change: 0.95 },
                { ticker: "META", name: "Meta Platforms", marketCap: 925, change: 1.65 },
                { ticker: "NFLX", name: "Netflix Inc.", marketCap: 245, change: 2.15 },
                { ticker: "DIS", name: "Walt Disney", marketCap: 175, change: -0.45 },
                { ticker: "CMCSA", name: "Comcast Corp.", marketCap: 165, change: -0.28 },
                { ticker: "VZ", name: "Verizon", marketCap: 165, change: 0.15 },
                { ticker: "T", name: "AT&T Inc.", marketCap: 125, change: -0.35 },
                { ticker: "TMUS", name: "T-Mobile US", marketCap: 195, change: 0.55 },
                { ticker: "CHTR", name: "Charter Comm.", marketCap: 55, change: -0.72 },
                { ticker: "WBD", name: "Warner Bros.", marketCap: 25, change: -1.85 },
                { ticker: "EA", name: "Electronic Arts", marketCap: 35, change: 0.42 },
                { ticker: "TTWO", name: "Take-Two", marketCap: 25, change: 0.65 },
                { ticker: "OMC", name: "Omnicom Group", marketCap: 20, change: 0.28 },
                { ticker: "IPG", name: "Interpublic", marketCap: 12, change: 0.35 },
                { ticker: "PARA", name: "Paramount", marketCap: 8, change: -2.45 },
                { ticker: "FOX", name: "Fox Corp.", marketCap: 15, change: 0.18 },
                { ticker: "NWSA", name: "News Corp.", marketCap: 15, change: 0.22 },
                { ticker: "LYV", name: "Live Nation", marketCap: 22, change: 0.85 },
                { ticker: "MTCH", name: "Match Group", marketCap: 10, change: -1.25 }
            ]
        },
        {
            name: "Consumer Staples",
            children: [
                { ticker: "WMT", name: "Walmart Inc.", marketCap: 425, change: 0.45 },
                { ticker: "PG", name: "Procter & Gamble", marketCap: 365, change: 0.28 },
                { ticker: "COST", name: "Costco", marketCap: 295, change: 0.85 },
                { ticker: "KO", name: "Coca-Cola", marketCap: 255, change: 0.15 },
                { ticker: "PEP", name: "PepsiCo", marketCap: 235, change: -0.22 },
                { ticker: "PM", name: "Philip Morris", marketCap: 155, change: 0.35 },
                { ticker: "MO", name: "Altria Group", marketCap: 85, change: -0.18 },
                { ticker: "MDLZ", name: "Mondelez", marketCap: 95, change: 0.42 },
                { ticker: "CL", name: "Colgate-Palmolive", marketCap: 75, change: 0.28 },
                { ticker: "EL", name: "Estee Lauder", marketCap: 55, change: -0.65 },
                { ticker: "KMB", name: "Kimberly-Clark", marketCap: 45, change: 0.18 },
                { ticker: "GIS", name: "General Mills", marketCap: 40, change: -0.32 },
                { ticker: "SYY", name: "Sysco Corp.", marketCap: 40, change: 0.45 },
                { ticker: "HSY", name: "Hershey Co.", marketCap: 45, change: -0.55 },
                { ticker: "K", name: "Kellanova", marketCap: 25, change: 0.22 },
                { ticker: "KHC", name: "Kraft Heinz", marketCap: 45, change: -0.28 },
                { ticker: "STZ", name: "Constellation Brands", marketCap: 45, change: 0.55 },
                { ticker: "KR", name: "Kroger Co.", marketCap: 35, change: 0.15 },
                { ticker: "WBA", name: "Walgreens Boots", marketCap: 20, change: -1.45 },
                { ticker: "CAG", name: "Conagra Brands", marketCap: 15, change: -0.35 }
            ]
        },
        {
            name: "Energy",
            children: [
                { ticker: "XOM", name: "Exxon Mobil", marketCap: 455, change: -0.85 },
                { ticker: "CVX", name: "Chevron Corp.", marketCap: 285, change: -0.65 },
                { ticker: "COP", name: "ConocoPhillips", marketCap: 135, change: -0.95 },
                { ticker: "EOG", name: "EOG Resources", marketCap: 75, change: -0.72 },
                { ticker: "SLB", name: "Schlumberger", marketCap: 75, change: -0.55 },
                { ticker: "MPC", name: "Marathon Petroleum", marketCap: 60, change: -0.45 },
                { ticker: "PXD", name: "Pioneer Natural", marketCap: 55, change: -0.82 },
                { ticker: "PSX", name: "Phillips 66", marketCap: 50, change: -0.38 },
                { ticker: "VLO", name: "Valero Energy", marketCap: 45, change: -0.52 },
                { ticker: "OXY", name: "Occidental Petro", marketCap: 55, change: -1.15 },
                { ticker: "WMB", name: "Williams Cos.", marketCap: 45, change: 0.28 },
                { ticker: "KMI", name: "Kinder Morgan", marketCap: 40, change: 0.15 },
                { ticker: "HAL", name: "Halliburton", marketCap: 30, change: -0.65 },
                { ticker: "DVN", name: "Devon Energy", marketCap: 30, change: -0.78 },
                { ticker: "BKR", name: "Baker Hughes", marketCap: 30, change: -0.42 },
                { ticker: "FANG", name: "Diamondback Energy", marketCap: 35, change: -0.55 },
                { ticker: "HES", name: "Hess Corp.", marketCap: 45, change: -0.35 },
                { ticker: "TRGP", name: "Targa Resources", marketCap: 25, change: 0.45 },
                { ticker: "OKE", name: "ONEOK Inc.", marketCap: 35, change: 0.32 }
            ]
        },
        {
            name: "Industrials",
            children: [
                { ticker: "GE", name: "GE Aerospace", marketCap: 175, change: 1.25 },
                { ticker: "CAT", name: "Caterpillar", marketCap: 165, change: 0.75 },
                { ticker: "UNP", name: "Union Pacific", marketCap: 145, change: 0.35 },
                { ticker: "RTX", name: "RTX Corp.", marketCap: 140, change: 0.55 },
                { ticker: "HON", name: "Honeywell", marketCap: 135, change: 0.28 },
                { ticker: "BA", name: "Boeing Co.", marketCap: 115, change: -1.85 },
                { ticker: "DE", name: "Deere & Co.", marketCap: 110, change: 0.65 },
                { ticker: "LMT", name: "Lockheed Martin", marketCap: 115, change: 0.42 },
                { ticker: "UPS", name: "United Parcel", marketCap: 100, change: -0.35 },
                { ticker: "ADP", name: "ADP Inc.", marketCap: 105, change: 0.48 },
                { ticker: "ETN", name: "Eaton Corp.", marketCap: 95, change: 0.85 },
                { ticker: "NOC", name: "Northrop Grumman", marketCap: 75, change: 0.55 },
                { ticker: "GD", name: "General Dynamics", marketCap: 75, change: 0.38 },
                { ticker: "WM", name: "Waste Management", marketCap: 80, change: 0.22 },
                { ticker: "ITW", name: "Illinois Tool Works", marketCap: 75, change: 0.32 },
                { ticker: "FDX", name: "FedEx Corp.", marketCap: 65, change: -0.55 },
                { ticker: "EMR", name: "Emerson Electric", marketCap: 60, change: 0.45 },
                { ticker: "NSC", name: "Norfolk Southern", marketCap: 55, change: 0.28 },
                { ticker: "CSX", name: "CSX Corp.", marketCap: 65, change: 0.35 },
                { ticker: "PH", name: "Parker Hannifin", marketCap: 65, change: 0.72 }
            ]
        },
        {
            name: "Utilities",
            children: [
                { ticker: "NEE", name: "NextEra Energy", marketCap: 145, change: 0.45 },
                { ticker: "SO", name: "Southern Co.", marketCap: 85, change: 0.28 },
                { ticker: "DUK", name: "Duke Energy", marketCap: 80, change: 0.22 },
                { ticker: "SRE", name: "Sempra Energy", marketCap: 50, change: 0.35 },
                { ticker: "AEP", name: "American Electric", marketCap: 50, change: 0.18 },
                { ticker: "D", name: "Dominion Energy", marketCap: 45, change: -0.15 },
                { ticker: "EXC", name: "Exelon Corp.", marketCap: 40, change: 0.32 },
                { ticker: "XEL", name: "Xcel Energy", marketCap: 35, change: 0.25 },
                { ticker: "PCG", name: "PG&E Corp.", marketCap: 35, change: 0.42 },
                { ticker: "ED", name: "Con Edison", marketCap: 30, change: 0.15 },
                { ticker: "WEC", name: "WEC Energy", marketCap: 30, change: 0.28 },
                { ticker: "EIX", name: "Edison Intl", marketCap: 30, change: 0.35 },
                { ticker: "AWK", name: "American Water", marketCap: 25, change: 0.22 },
                { ticker: "DTE", name: "DTE Energy", marketCap: 25, change: 0.18 },
                { ticker: "PPL", name: "PPL Corp.", marketCap: 22, change: 0.12 },
                { ticker: "ES", name: "Eversource", marketCap: 22, change: -0.25 },
                { ticker: "FE", name: "FirstEnergy", marketCap: 22, change: 0.28 },
                { ticker: "AEE", name: "Ameren Corp.", marketCap: 22, change: 0.22 },
                { ticker: "CMS", name: "CMS Energy", marketCap: 18, change: 0.15 },
                { ticker: "CNP", name: "CenterPoint", marketCap: 18, change: 0.32 }
            ]
        },
        {
            name: "Real Estate",
            children: [
                { ticker: "PLD", name: "Prologis", marketCap: 115, change: 0.55 },
                { ticker: "AMT", name: "American Tower", marketCap: 95, change: 0.42 },
                { ticker: "EQIX", name: "Equinix", marketCap: 75, change: 0.85 },
                { ticker: "CCI", name: "Crown Castle", marketCap: 45, change: 0.28 },
                { ticker: "PSA", name: "Public Storage", marketCap: 55, change: 0.35 },
                { ticker: "SPG", name: "Simon Property", marketCap: 50, change: -0.22 },
                { ticker: "WELL", name: "Welltower", marketCap: 50, change: 0.48 },
                { ticker: "DLR", name: "Digital Realty", marketCap: 40, change: 0.72 },
                { ticker: "O", name: "Realty Income", marketCap: 45, change: 0.25 },
                { ticker: "VICI", name: "VICI Properties", marketCap: 35, change: 0.38 },
                { ticker: "AVB", name: "AvalonBay", marketCap: 30, change: 0.22 },
                { ticker: "EQR", name: "Equity Residential", marketCap: 25, change: 0.18 },
                { ticker: "SBAC", name: "SBA Comm.", marketCap: 25, change: 0.35 },
                { ticker: "WY", name: "Weyerhaeuser", marketCap: 25, change: -0.15 },
                { ticker: "ARE", name: "Alexandria RE", marketCap: 20, change: 0.45 },
                { ticker: "EXR", name: "Extra Space", marketCap: 35, change: 0.28 },
                { ticker: "MAA", name: "Mid-America Apt", marketCap: 18, change: 0.22 },
                { ticker: "VTR", name: "Ventas Inc.", marketCap: 20, change: 0.35 },
                { ticker: "IRM", name: "Iron Mountain", marketCap: 25, change: 0.55 },
                { ticker: "CBRE", name: "CBRE Group", marketCap: 30, change: 0.42 }
            ]
        },
        {
            name: "Materials",
            children: [
                { ticker: "LIN", name: "Linde plc", marketCap: 205, change: 0.65 },
                { ticker: "APD", name: "Air Products", marketCap: 65, change: 0.42 },
                { ticker: "SHW", name: "Sherwin-Williams", marketCap: 85, change: 0.55 },
                { ticker: "FCX", name: "Freeport-McMoRan", marketCap: 60, change: -0.85 },
                { ticker: "ECL", name: "Ecolab Inc.", marketCap: 55, change: 0.38 },
                { ticker: "NUE", name: "Nucor Corp.", marketCap: 40, change: -0.55 },
                { ticker: "NEM", name: "Newmont Corp.", marketCap: 40, change: 1.25 },
                { ticker: "DOW", name: "Dow Inc.", marketCap: 40, change: -0.42 },
                { ticker: "CTVA", name: "Corteva", marketCap: 35, change: 0.28 },
                { ticker: "DD", name: "DuPont", marketCap: 35, change: 0.35 },
                { ticker: "PPG", name: "PPG Industries", marketCap: 35, change: 0.45 },
                { ticker: "VMC", name: "Vulcan Materials", marketCap: 30, change: 0.62 },
                { ticker: "MLM", name: "Martin Marietta", marketCap: 30, change: 0.55 },
                { ticker: "ALB", name: "Albemarle", marketCap: 15, change: -1.85 },
                { ticker: "IFF", name: "IFF", marketCap: 22, change: 0.28 },
                { ticker: "LYB", name: "LyondellBasell", marketCap: 25, change: -0.35 },
                { ticker: "CF", name: "CF Industries", marketCap: 15, change: 0.45 },
                { ticker: "MOS", name: "Mosaic Co.", marketCap: 12, change: -0.55 },
                { ticker: "CE", name: "Celanese", marketCap: 15, change: 0.32 },
                { ticker: "BALL", name: "Ball Corp.", marketCap: 18, change: 0.22 }
            ]
        }
    ]
};
